version: '3.3'

services:
  app:
    build: ./
    command: ./reverse-proxy
    ports:
      - 8080:8080
    depends_on:
      - rdb
    restart: always
  rdb:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - ./.database/data:/var/lib/redis/data
    restart: always